In [1]:
import numpy as np

### Matrix Addition

#### Two matrices can be added only if they have the same shape

In [2]:
#creating two matrices 

a = np.array([[2,3],[4,5]])
b = np.array([[6,7],[8,9]])

print(a)
print(b)

[[2 3]
 [4 5]]
[[6 7]
 [8 9]]


In [3]:
print(a.shape)
print(b.shape)

(2, 2)
(2, 2)


#### Adding two matrices

In [4]:
sum = a + b
print(sum)

[[ 8 10]
 [12 14]]


In [7]:
# create two matrices with random values
matrix_1 = np.random.randint(10,size=(3,3))
matrix_2 = np.random.randint(20,size=(3,3))

In [8]:
print(matrix_1)

[[4 7 6]
 [9 7 7]
 [3 7 1]]


In [9]:
print(matrix_2)

[[ 6 13  6]
 [ 7 17 16]
 [11 12 10]]


In [10]:
sum = np.add(matrix_1,matrix_2)

In [11]:
print(sum)

[[10 20 12]
 [16 24 23]
 [14 19 11]]


In [13]:
# create two matrices with random values
matrix_3 = np.random.randint(10,size=(3,3))
matrix_4= np.random.randint(20,size=(3,4))

In [14]:
sum_2 = np.add(matrix_3,matrix_4)

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

We get this error because the shape of matrix_3 and matrix_4 are different

### Matrix Subtraction

In [15]:
#creating two matrices 

a = np.array([[2,3],[4,5]])
b = np.array([[6,7],[8,9]])

print(a)
print(b)

[[2 3]
 [4 5]]
[[6 7]
 [8 9]]


In [16]:
difference = a - b

In [17]:
print(difference)

[[-4 -4]
 [-4 -4]]


In [18]:
# create two matrices with random values
matrix_1 = np.random.randint(10,size=(3,3))
matrix_2 = np.random.randint(20,size=(3,3))

In [19]:
print(matrix_1)

[[7 4 8]
 [2 2 7]
 [2 4 4]]


In [20]:
print(matrix_2)

[[15 14 12]
 [15 13 13]
 [18 17 13]]


In [22]:
difference = np.subtract(matrix_1,matrix_2)

In [23]:
print(difference)

[[ -8 -10  -4]
 [-13 -11  -6]
 [-16 -13  -9]]


In [24]:
# create two matrices with random values
matrix_3 = np.random.randint(10,size=(3,3))
matrix_4= np.random.randint(20,size=(3,4))

In [25]:
difference = np.subtract(matrix_3,matrix_4)

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

### Multiplying a matrix by a scaler

In [26]:
x = 5
y = np.random.randint(10,size=(4,4))

print(y)

[[1 1 5 3]
 [9 7 0 4]
 [7 3 5 6]
 [0 3 5 0]]


In [27]:
product = np.multiply(x,y)

In [28]:
print(product)

[[ 5  5 25 15]
 [45 35  0 20]
 [35 15 25 30]
 [ 0 15 25  0]]


### Multiplying two matrices

In [29]:
# create two matrices with random values
matrix_1 = np.random.randint(5,size=(3,3))
matrix_2 = np.random.randint(5,size=(3,4))

In [30]:
print(matrix_1)

[[1 0 2]
 [3 4 4]
 [0 3 1]]


In [31]:
print(matrix_2)

[[3 3 2 3]
 [1 0 2 3]
 [4 0 4 3]]


In [32]:
product = np.dot(matrix_1,matrix_2)

In [33]:
print(product)

[[11  3 10  9]
 [29  9 30 33]
 [ 7  0 10 12]]


In [34]:
product.shape

(3, 4)