In [1]:
import numpy as np

### Creating a matrix using numpy

In [2]:
matrix_1 = np.array([[2,3],[6,7]])

In [3]:
print(matrix_1)

[[2 3]
 [6 7]]


### Shape of matrix

In [4]:
matrix_1.shape

(2, 2)

In [7]:
matrix_2 = np.array([[3,4,5],[1,5,9],[8,9,1]])
print(matrix_2)

[[3 4 5]
 [1 5 9]
 [8 9 1]]


In [8]:
matrix_2.shape

(3, 3)

### Creating matrices with Random Values

In [9]:
random_matrix = np.random.rand(3,3)

In [10]:
print(random_matrix)

[[0.05748183 0.08044794 0.97775741]
 [0.13295604 0.97514394 0.14956645]
 [0.04295387 0.8304174  0.60200001]]


### Creating matrices with Random Integer

In [14]:
random_matrix1 = np.random.randint(100,size=(4,5))#100-->no's within 100 and size -->4 rows and 5 columns

In [16]:
print(random_matrix1)

[[ 1 99 55 63 78]
 [53 81 14 85 94]
 [46 92 29 16 24]
 [95 80 57 12 14]]


### Creating matrices with all the values 1

In [17]:
matrix_3 = np.ones((2,3))
print(matrix_3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [20]:
matrix_3 = np.ones((2,3),dtype=int) #all the value in integer, we should give dtype
print(matrix_3)

[[1 1 1]
 [1 1 1]]


In [21]:
matrix_4 = np.ones((10,10),dtype=int) #all the value in integer, we should give dtype
print(matrix_4)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


### Creating matrix with Zero or Null matrix

In [22]:
null_matrix = np.zeros((4,4))
print(null_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [23]:
null_matrix = np.zeros((4,4),dtype=int)
print(null_matrix)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


# Creating Identity Matrix

In [24]:
identity_matrix = np.eye(3,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
identity_matrix = np.eye(5,5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# Transpose of a matrix

In [26]:
#matrix with random integer value
a = np.random.randint(100,size=(4,5))
print(a)

[[19 61 11 72 20]
 [24 95  9 99 30]
 [42 58  8  4  0]
 [37 95 48 54 43]]


In [27]:
transpose_a = np.transpose(a)

In [28]:
print(transpose_a)

[[19 24 42 37]
 [61 95 58 95]
 [11  9  8 48]
 [72 99  4 54]
 [20 30  0 43]]
